
default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: PDF_development

test:
  <<: *default
  database: PDF_test

#   production:
#     url: <%= ENV['MY_APP_DATABASE_URL'] %>
production:
  <<: *default
  database: PDF_production
  username: PDF
  password: <%= ENV['PDF_DATABASE_PASSWORD'] %>
